name: tree_animation
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  flutter_svg: ^2.0.9
  formz: ^0.4.1
  device_info_plus: ^8.2.2
  package_info_plus: ^5.0.1
  dio: ^5.4.0
  pin_input_text_field: ^4.1.1
  logger: ^2.0.2+1
  responsive_builder: ^0.7.0
  dotted_border:
  dotted_line: ^3.1.0
  equatable: ^2.0.5
  shared_preferences: ^2.0.15
  intl: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: helvetica
      fonts:
        - asset: "assets/fonts/Helvetica/Helvetica.ttf"
        - asset: "assets/fonts/Helvetica/Helvetica-Bold.ttf"
        - asset: "assets/fonts/Helvetica/Helvetica-BoldOblique.ttf"
        - asset: "assets/fonts/Helvetica/Helvetica-Oblique.ttf"
    - family: Marker Felt
      fonts:
        - asset: "assets/fonts/Marker Felt/Marker Felt.ttf"
    - family: Ubuntu
      fonts:
        - asset: "assets/fonts/Ubuntu/Ubuntu-Italic.ttf"
        - asset: "assets/fonts/Ubuntu/Ubuntu-Bold.ttf"
        - asset: "assets/fonts/Ubuntu/Ubuntu-BoldItalic.ttf"
        - asset: "assets/fonts/Ubuntu/Ubuntu-Medium.ttf"
        - asset: "assets/fonts/Ubuntu/Ubuntu-Light.ttf"
    - family: Roboto
      fonts:
        - asset: "assets/fonts/Roboto/Roboto-Bold.ttf"
        - asset: "assets/fonts/Roboto/Roboto-BoldItalic.ttf"
        - asset: "assets/fonts/Roboto/Roboto-Italic.ttf"
        - asset: "assets/fonts/Roboto/Roboto-Light.ttf"
        - asset: "assets/fonts/Roboto/Roboto-LightItalic.ttf"
        - asset: "assets/fonts/Roboto/Roboto-Medium.ttf"
        - asset: "assets/fonts/Roboto/Roboto-MediumItalic.ttf"
        - asset: "assets/fonts/Roboto/Roboto-Regular.ttf"
        - asset: "assets/fonts/Roboto/Roboto-Thin.ttf"
        - asset: "assets/fonts/Roboto/Roboto-ThinItalic.ttf"

    - family: JD
      fonts:
        - asset: "assets/fonts/J.d/j.d.ttf"
    - family: Gilroy
      fonts:
        - asset: "assets/fonts/gilroy/Gilroy-Regular.ttf"
        - asset: "assets/fonts/gilroy/Gilroy-Bold.ttf"
        - asset: "assets/fonts/gilroy/Gilroy-Medium.ttf"

    - family: proxima_nova_soft_regular
      fonts:
        #        - asset: "assets/fonts/proxima_nova_soft_regular/proxima-nova-alt-bold.otf"
        #        - asset: "assets/fonts/proxima_nova_soft_regular/proxima-nova-alt-light.otf"
        #        - asset: "assets/fonts/proxima_nova_soft_regular/proxima-nova-alt-thin.otf"
        #        - asset: "assets/fonts/proxima_nova_soft_regular/proxima-nova-black.otf"
        #        - asset: "assets/fonts/proxima_nova_soft_regular/proxima-nova-bold.otf"
        #        - asset: "assets/fonts/proxima_nova_soft_regular/proxima-nova-extrabold.otf"
        - asset: "assets/fonts/proxima_nova_soft_regular/proxima-nova-regular.otf"
#        - asset: "assets/fonts/proxima_nova_soft_regular/proxima-nova-thin.otf"